"""Export a DynamicGrade graph as DaVinci Resolve-compatible 3D LUTs."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Sequence

import numpy as np
import torch

from retouch_agent import RetouchExecutor, RetouchParameters
from retouch_agent.parameters import PARAMETER_NAMES

from .models import GradeGraph


def compress_parameter_trajectory(
    trajectory: np.ndarray,
    *,
    maximum_error: float = 0.015,
    mandatory_indices: Sequence[int] = (),
) -> tuple[int, ...]:
    """Reduce a dense trajectory to linear keyframes within a max error bound."""

    values = np.asarray(trajectory, dtype=np.float64)
    if values.ndim != 2 or values.shape[1] != len(PARAMETER_NAMES):
        raise ValueError("Trajectory must have shape [frames, parameters].")
    if values.shape[0] < 1 or not np.all(np.isfinite(values)):
        raise ValueError("Trajectory must contain finite frame parameters.")
    if maximum_error < 0:
        raise ValueError("maximum_error cannot be negative.")
    required = {0, values.shape[0] - 1}
    for index in mandatory_indices:
        value = int(index)
        if not 0 <= value < values.shape[0]:
            raise IndexError("Mandatory trajectory keyframe is outside the shot.")
        required.add(value)

    selected = set(required)

    def refine(start: int, end: int) -> None:
        if end <= start + 1:
            return
        offsets = np.arange(start + 1, end, dtype=np.float64)
        amount = ((offsets - start) / (end - start))[:, None]
        estimate = values[start] + amount * (values[end] - values[start])
        errors = np.max(np.abs(values[start + 1 : end] - estimate), axis=1)
        worst_offset = int(np.argmax(errors))
        if float(errors[worst_offset]) > maximum_error:
            split = start + 1 + worst_offset
            selected.add(split)
            refine(start, split)
            refine(split, end)

    ordered_required = sorted(required)
    for start, end in zip(ordered_required[:-1], ordered_required[1:]):
        refine(start, end)
    return tuple(sorted(selected))


def _dctl_float(value: float) -> str:
    text = f"{float(value):.9g}"
    if "." not in text and "e" not in text.lower():
        text += ".0"
    return text + "f"


def write_dynamic_dctl(
    trajectory: np.ndarray,
    path: Path,
    *,
    timeline_start_frame: int,
    maximum_error: float = 0.015,
    mandatory_indices: Sequence[int] = (),
) -> tuple[Path, tuple[int, ...]]:
    """Write a time-aware DCTL matching the deterministic global executor."""

    values = np.asarray(trajectory, dtype=np.float64)
    if np.any(np.abs(values[:, 9:]) > 1e-8):
        raise ValueError("Dynamic DCTL cannot encode local-mask parameters.")
    keyframes = compress_parameter_trajectory(
        values,
        maximum_error=maximum_error,
        mandatory_indices=mandatory_indices,
    )
    names = PARAMETER_NAMES[:9]
    assignments: list[str] = []
    first = keyframes[0]
    assignments.append(f"    if (dg_frame <= {_dctl_float(first)}) {{")
    assignments.extend(
        f"        {name} = {_dctl_float(values[first, index])};"
        for index, name in enumerate(names)
    )
    assignments.append("    }")
    for start, end in zip(keyframes[:-1], keyframes[1:]):
        assignments.append(f"    else if (dg_frame <= {_dctl_float(end)}) {{")
        assignments.append(
            "        float dg_u = (dg_frame - "
            f"{_dctl_float(start)}) / {_dctl_float(end - start)};"
        )
        assignments.extend(
            f"        {name} = {_dctl_float(values[start, index])} + "
            f"({_dctl_float(values[end, index] - values[start, index])}) * dg_u;"
            for index, name in enumerate(names)
        )
        assignments.append("    }")
    last = keyframes[-1]
    assignments.append("    else {")
    assignments.extend(
        f"        {name} = {_dctl_float(values[last, index])};"
        for index, name in enumerate(names)
    )
    assignments.append("    }")

    declarations = "\n".join(f"    float {name} = 0.0f;" for name in names)
    source = f"""// Generated by DynamicGrade. Resolve 19.1+ required.
// The apply script rewrites this origin to the matched timeline clip start.
#define DG_TIMELINE_START {_dctl_float(timeline_start_frame)}

__DEVICE__ float dg_clamp(float value, float low, float high)
{{
    return _fminf(_fmaxf(value, low), high);
}}

__DEVICE__ float dg_srgb_to_linear(float value)
{{
    value = _fmaxf(value, 0.0f);
    return value <= 0.04045f
        ? value / 12.92f
        : _powf((value + 0.055f) / 1.055f, 2.4f);
}}

__DEVICE__ float dg_linear_to_srgb(float value)
{{
    value = _fmaxf(value, 0.0f);
    return value <= 0.0031308f
        ? value * 12.92f
        : 1.055f * _powf(value, 1.0f / 2.4f) - 0.055f;
}}

__DEVICE__ float3 transform(
    int p_Width, int p_Height, int p_X, int p_Y,
    float p_R, float p_G, float p_B)
{{
    float dg_frame = (float)TIMELINE_FRAME_INDEX - DG_TIMELINE_START;
{declarations}
{chr(10).join(assignments)}

    float red = dg_srgb_to_linear(p_R);
    float green = dg_srgb_to_linear(p_G);
    float blue = dg_srgb_to_linear(p_B);
    float exposure_gain = _powf(2.0f, exposure);
    red *= exposure_gain * _expf(0.28f * temperature + 0.10f * tint);
    green *= exposure_gain * _expf(-0.16f * tint);
    blue *= exposure_gain * _expf(-0.28f * temperature + 0.10f * tint);

    float luminance = dg_clamp(
        0.2126f * red + 0.7152f * green + 0.0722f * blue, 0.0f, 1.0f);
    float highlight_weight = luminance * luminance;
    float shadow_weight = (1.0f - luminance) * (1.0f - luminance);
    float scale = _fmaxf(
        1.0f + 0.55f * highlights * highlight_weight
        + 0.55f * shadows * shadow_weight,
        0.05f);
    red *= scale;
    green *= scale;
    blue *= scale;

    float contrast_factor = _powf(2.0f, contrast);
    red = (red - 0.18f) * contrast_factor + 0.18f;
    green = (green - 0.18f) * contrast_factor + 0.18f;
    blue = (blue - 0.18f) * contrast_factor + 0.18f;
    float gamma = _expf(-0.70f * tone_curve);
    red = _powf(_fmaxf(red, 0.0000001f), gamma);
    green = _powf(_fmaxf(green, 0.0000001f), gamma);
    blue = _powf(_fmaxf(blue, 0.0000001f), gamma);

    red = dg_linear_to_srgb(red);
    green = dg_linear_to_srgb(green);
    blue = dg_linear_to_srgb(blue);
    float srgb_luma = 0.2126f * red + 0.7152f * green + 0.0722f * blue;
    float saturation_factor = dg_clamp(1.0f + saturation, 0.0f, 2.0f);
    red = srgb_luma + saturation_factor * (red - srgb_luma);
    green = srgb_luma + saturation_factor * (green - srgb_luma);
    blue = srgb_luma + saturation_factor * (blue - srgb_luma);

    float maximum = _fmaxf(red, _fmaxf(green, blue));
    float minimum = _fminf(red, _fminf(green, blue));
    float spread = dg_clamp(maximum - minimum, 0.0f, 1.0f);
    float vibrance_factor = dg_clamp(
        1.0f + vibrance * (1.0f - spread), 0.0f, 2.0f);
    red = srgb_luma + vibrance_factor * (red - srgb_luma);
    green = srgb_luma + vibrance_factor * (green - srgb_luma);
    blue = srgb_luma + vibrance_factor * (blue - srgb_luma);
    return make_float3(
        dg_clamp(red, 0.0f, 1.0f),
        dg_clamp(green, 0.0f, 1.0f),
        dg_clamp(blue, 0.0f, 1.0f));
}}
"""
    path = Path(path).resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source, encoding="utf-8")
    return path, keyframes


def _write_resolve_apply_script(output_dir: Path) -> Path:
    script_path = output_dir / "apply_dynamic_grade.py"
    source = '''"""Install and apply DynamicGrade DCTLs to a conformed Resolve timeline."""
import argparse
import json
from pathlib import Path
import re

import DaVinciResolveScript as dvr_script


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, default=Path(__file__).with_name("resolve_manifest.json"))
    parser.add_argument("--lut-dir", type=Path, required=True, help="A directory inside Resolve's configured LUT search paths.")
    parser.add_argument("--video-track", type=int, default=1)
    parser.add_argument("--node-index", type=int, required=True, help="Existing dedicated empty Color node to replace with the dynamic DCTL.")
    args = parser.parse_args()
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    resolve = dvr_script.scriptapp("Resolve")
    if resolve is None:
        raise RuntimeError("DaVinci Resolve is not running or scripting is unavailable.")
    project = resolve.GetProjectManager().GetCurrentProject()
    timeline = None if project is None else project.GetCurrentTimeline()
    if timeline is None:
        raise RuntimeError("Open the target project and timeline first.")
    clips = list(timeline.GetItemListInTrack("video", args.video_track) or [])
    shots = manifest["shots"]
    if len(clips) != len(shots):
        raise RuntimeError("Timeline must be conformed to exactly one clip per manifest shot.")
    clips.sort(key=lambda item: int(item.GetStart()))
    shots = sorted(shots, key=lambda item: int(item["start_frame"]))
    destination = args.lut_dir.resolve() / "DynamicGrade" / args.manifest.parent.name
    destination.mkdir(parents=True, exist_ok=True)
    pending = []
    for clip, shot in zip(clips, shots):
        expected = int(shot["end_frame"]) - int(shot["start_frame"]) + 1
        if int(clip.GetDuration()) != expected:
            raise RuntimeError(f"Shot {shot['shot_id']} duration does not match timeline clip.")
        if args.node_index < 1 or args.node_index > int(clip.GetNumNodes()):
            raise RuntimeError(f"Shot {shot['shot_id']} has no Color node {args.node_index}.")
        template = Path(shot["dynamic_dctl"])
        text = template.read_text(encoding="utf-8")
        origin = f"{float(clip.GetStart()):.9g}"
        if "." not in origin and "e" not in origin.lower():
            origin += ".0"
        text = re.sub(
            r"#define DG_TIMELINE_START [-+0-9.eE]+f",
            f"#define DG_TIMELINE_START {origin}f",
            text,
            count=1,
        )
        target = destination / template.name
        target.write_text(text, encoding="utf-8")
        pending.append((clip, shot, target))
    if not project.RefreshLUTList():
        raise RuntimeError("Resolve failed to refresh its LUT list.")
    for clip, shot, target in pending:
        if not clip.SetLUT(args.node_index, str(target)):
            raise RuntimeError(f"Failed to apply dynamic DCTL for shot {shot['shot_id']}.")
    project.SaveProject()
    print(f"Applied {len(pending)} DynamicGrade DCTLs.")


if __name__ == "__main__":
    main()
'''
    script_path.write_text(source, encoding="utf-8")
    return script_path


def write_cube_lut(
    parameters: RetouchParameters,
    path: Path,
    *,
    size: int = 33,
    title: str = "DynamicGrade",
) -> Path:
    """Write an RGB 3D LUT matching the deterministic global executor."""

    if size < 2 or size > 65:
        raise ValueError("Resolve LUT size must be between 2 and 65.")
    values = parameters.to_vector(np.float32)
    if np.any(np.abs(values[9:]) > 1e-8):
        raise ValueError("A global 3D LUT cannot encode local-mask parameters.")

    axis = np.linspace(0.0, 1.0, size, dtype=np.float32)
    # .cube order changes red fastest, then green, then blue.
    grid = np.asarray(
        [(red, green, blue) for blue in axis for green in axis for red in axis],
        dtype=np.float32,
    )
    pixels = torch.from_numpy(grid).reshape(-1, 3, 1, 1)
    with torch.inference_mode():
        output = RetouchExecutor().apply_vector(
            pixels,
            torch.from_numpy(values),
        )
    transformed = output[:, :, 0, 0].cpu().numpy()

    path = Path(path).resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        f'TITLE "{title}"',
        f"LUT_3D_SIZE {size}",
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
    ]
    body = ["{:.8f} {:.8f} {:.8f}".format(*row) for row in transformed]
    path.write_text("\n".join([*header, *body]) + "\n", encoding="utf-8")
    return path


def export_resolve_package(
    grade: GradeGraph,
    source_video: Path,
    output_dir: Path,
    *,
    lut_size: int = 33,
    dynamic_keyframe_error: float = 0.015,
) -> Path:
    """Export static LUTs and time-aware DCTL trajectories for Resolve."""

    output_dir = Path(output_dir).resolve()
    lut_dir = output_dir / "LUT"
    dctl_dir = output_dir / "DCTL"
    lut_dir.mkdir(parents=True, exist_ok=True)
    shots = []
    for shot_grade in grade.shots:
        parameters = RetouchParameters.from_vector(shot_grade.base_parameters)
        lut_path = write_cube_lut(
            parameters,
            lut_dir / f"shot-{shot_grade.shot.shot_id:04d}.cube",
            size=lut_size,
            title=f"DynamicGrade shot {shot_grade.shot.shot_id}",
        )
        mandatory = [
            int(index) - shot_grade.shot.start_frame
            for index in shot_grade.parameter_keyframes
        ]
        dctl_path, dynamic_keyframes = write_dynamic_dctl(
            shot_grade.frame_parameters,
            dctl_dir / f"shot-{shot_grade.shot.shot_id:04d}.dctl",
            timeline_start_frame=shot_grade.shot.start_frame,
            maximum_error=dynamic_keyframe_error,
            mandatory_indices=mandatory,
        )
        shots.append(
            {
                "shot_id": shot_grade.shot.shot_id,
                "start_frame": shot_grade.shot.start_frame,
                "end_frame": shot_grade.shot.end_frame,
                "lut": str(lut_path),
                "dynamic_dctl": str(dctl_path),
                "dynamic_keyframes": [
                    {
                        "frame": shot_grade.shot.start_frame + index,
                        "parameters": dict(
                            zip(
                                PARAMETER_NAMES,
                                shot_grade.frame_parameters[index].tolist(),
                            )
                        ),
                    }
                    for index in dynamic_keyframes
                ],
                "parameters": dict(
                    zip(PARAMETER_NAMES, shot_grade.base_parameters.tolist())
                ),
                "accepted": shot_grade.accepted,
                "rolled_back": shot_grade.rolled_back,
                "rollback_reason": shot_grade.rollback_reason,
            }
        )
    manifest = {
        "schema_version": "dynamic-grade-resolve-package/v1",
        "source_video": str(Path(source_video).resolve()),
        "fps": grade.storyboard.fps,
        "frame_count": grade.storyboard.frame_count,
        "color_pipeline": {
            "lut_domain": "display-referred RGB [0,1]",
            "recommended_timeline": "Rec.709 Gamma 2.4",
            "lut_size": lut_size,
            "dynamic_keyframe_max_error": dynamic_keyframe_error,
        },
        "shots": shots,
        "dynamic_apply_script": str(
            _write_resolve_apply_script(output_dir).resolve()
        ),
        "resolve_status": (
            "Static LUTs and Resolve 19.1+ time-aware DCTLs are ready. The "
            "generated script applies DCTLs to an existing dedicated Color node."
        ),
    }
    manifest_path = output_dir / "resolve_manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    return manifest_path
